name: Spring Boot CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21 (Temurin)
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Set environment variables (MongoDB)
      run: |
        echo "APPLICATION_NAME=${{ secrets.APPLICATION_NAME }}" >> $GITHUB_ENV
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV

    - name: Build & Package with Maven (skip tests)
      run: mvn -B clean package -DskipTests --file pom.xml

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: springboot-app
        path: target/*.jar
