name: Spring Boot CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set environment variables (MongoDB)
      run: |
        echo "APPLICATION_NAME=${{ secrets.APPLICATION_NAME }}" >> $GITHUB_ENV
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV

    - name: Build and Package with Maven (skip tests)
      run: cd API_Rest && mvn -B clean package -DskipTests --file pom.xml

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: springboot-app
        path: API_Rest/target/*.jar
